# Generated by Django 2.0.5 on 2018-06-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_client_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='name',
            field=models.CharField(max_length=40),
            preserve_default=False,
        ),
    ]
