# Generated by Django 2.0.5 on 2018-06-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_deposit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
