# Generated by Django 2.0.5 on 2018-06-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_deposit_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='comment',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
